---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: querier
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: querier
    spec:
      containers:
        - name: querier
          image: quay.io/cortexproject/cortex
          imagePullPolicy: IfNotPresent
          args:
            - -target=querier
            - -server.http-listen-port=80
            - -consul.hostname=consul.default.svc.cluster.local:8500
            - -s3.url=s3://abc:123@s3.default.svc.cluster.local:4569
            - -querier.frontend-address=query-frontend.default.svc.cluster.local:9095
            - -dynamodb.original-table-name=cortex
            - -dynamodb.url=dynamodb://user:pass@dynamodb.default.svc.cluster.local:8000
            - -dynamodb.periodic-table.prefix=cortex_weekly_
            - -dynamodb.v9-schema-from=2019-11-01
            - -dynamodb.chunk-table.from=2017-04-17
            - -memcached.hostname=memcached.default.svc.cluster.local
            - -memcached.timeout=100ms
            - -memcached.service=memcached
            - -distributor.replication-factor=1
          ports:
            - containerPort: 80
