---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ruler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ruler
    spec:
      containers:
        - name: ruler
          image: quay.io/cortexproject/cortex
          imagePullPolicy: IfNotPresent
          args:
            - -target=ruler
            - -log.level=debug
            - -server.http-listen-port=80
            - -ruler.configs.url=http://configs.default.svc.cluster.local:80
            - -ruler.alertmanager-url=http://alertmanager.default.svc.cluster.local/api/prom/alertmanager/
            - -consul.hostname=consul.default.svc.cluster.local:8500
            - -s3.url=s3://abc:123@default.svc.cluster.local:4569/s3
            - -dynamodb.original-table-name=cortex
            - -dynamodb.url=dynamodb://user:pass@dynamodb.default.svc.cluster.local:8000
            - -dynamodb.periodic-table.prefix=cortex_weekly_
            - -dynamodb.v9-schema-from=2019-11-01
            - -memcached.hostname=memcached.default.svc.cluster.local
            - -memcached.timeout=100ms
            - -memcached.service=memcached
            - -distributor.replication-factor=1
          ports:
            - containerPort: 80
